In [7]:
import pyspark
from pyspark.sql import SparkSession
from module.metric import main
import warnings
master = "local[3]"
appName = "Didomi Test"
warnings.filterwarnings("ignore")
spark = SparkSession.builder.master(master).appName(appName).getOrCreate()

In [2]:
# main fucntion return pyspark dataframe
# main function params: 
#     - spark_session: SparkSession
#     - list_path: list of json file paths
#     - parquet_path: written file path. By default "/Users/tchamdja/Documents/PySpark/Didomi/output/metric.parquet"

### Variables

#### Input

In [3]:
datehour_2021_01_23_10 =  "input/datehour=2021-01-23-10/part-00000-9b503de5-0d72-4099-a388-7fdcf6e16edb.c000.json"
datehour_2021_01_23_11 =  "input/datehour=2021-01-23-11/part-00000-3a6f210d-7806-462e-b32c-344dff538d70.c000.json"
all_path = [datehour_2021_01_23_10,datehour_2021_01_23_11]

#### Output

In [4]:
output_parquet_path = "/Users/tchamdja/Documents/PySpark/Didomi/output/metric.parquet"

## Test datehour_2021_01_23_11

In [8]:
df1  = main(spark_session = spark ,
            list_path = [datehour_2021_01_23_10],
            parquet_path = output_parquet_path)

------------------------------Deduplication of events-----------------------------------

        datehour                                    id  count
0  2021-01-23-10  efd79868-ae77-4a72-871a-e04d4499558e      2
1  2021-01-23-10  097f20f6-afb9-488b-a24b-0a5a76272dd8      2
2  2021-01-23-10  5df4169b-db31-41f4-ad9a-a5526b120435      2
------------------------------------------------------------------------------------------

----------------------------------------Parquet file path--------------------------

File write in  /Users/tchamdja/Documents/PySpark/Didomi/output/metric.parquet
------------------------------------------------------------------------------------

In [6]:
df1.toPandas()

,datehour,domain,country,pageviews,pageviews_with_consent,consents_asked,consents_asked_with_consent,consent_given,consents_given_with_consent,avg_pageviews_per_user
0,2021-01-23-10,my-other-website.com,ES,0,0,1,0,1,1,
1,2021-01-23-10,my-other-website.com,FR,1,0,1,0,1,0,1
2,2021-01-23-10,www.domain-A.eu,ES,4,2,1,0,1,1,4
3,2021-01-23-10,www.domain-A.eu,FR,4,3,1,0,3,3,4
4,2021-01-23-10,www.mywebsite.com,DE,0,0,0,0,2,2,
5,2021-01-23-10,www.mywebsite.com,ES,0,0,1,0,1,1,
6,2021-01-23-10,www.mywebsite.com,FR,7,3,3,0,3,2,3

## datehour_2021_01_23_10,  datehour_2021_01_23_11

In [9]:
df2  = main(spark_session = spark ,
            list_path = all_path,
            parquet_path = output_parquet_path)

------------------------------Deduplication of events-----------------------------------

        datehour                                    id  count
0  2021-01-23-10  efd79868-ae77-4a72-871a-e04d4499558e      2
1  2021-01-23-10  097f20f6-afb9-488b-a24b-0a5a76272dd8      2
2  2021-01-23-10  5df4169b-db31-41f4-ad9a-a5526b120435      2
3  2021-01-23-11  9322dc81-c609-4422-8dd1-48ea10f35113      2
4  2021-01-23-11  3bd10718-f6f7-4d9f-8acd-b0d9f845d9b6      2
------------------------------------------------------------------------------------------

----------------------------------------Parquet file path--------------------------

File write in  /Users/tchamdja/Documents/PySpark/Didomi/output/metric.parquet
------------------------------------------------------------------------------------

In [10]:
df2.toPandas()

,datehour,domain,country,pageviews,pageviews_with_consent,consents_asked,consents_asked_with_consent,consent_given,consents_given_with_consent,avg_pageviews_per_user
0,2021-01-23-10,my-other-website.com,ES,0,0,1,0,1,1,
1,2021-01-23-10,my-other-website.com,FR,1,0,1,0,1,0,1
2,2021-01-23-10,www.domain-A.eu,ES,4,2,1,0,1,1,4
3,2021-01-23-10,www.domain-A.eu,FR,4,3,1,0,3,3,4
4,2021-01-23-10,www.mywebsite.com,DE,0,0,0,0,2,2,
5,2021-01-23-10,www.mywebsite.com,ES,0,0,1,0,1,1,
6,2021-01-23-10,www.mywebsite.com,FR,7,3,3,0,3,2,3
7,2021-01-23-11,www.domain-A.eu,ES,9,3,2,0,2,1,5
8,2021-01-23-11,www.mywebsite.com,DE,4,3,1,0,1,1,4
9,2021-01-23-11,www.mywebsite.com,FR,2,2,0,0,0,0,2

In [12]:
spark.stop()